name: AI CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  package-fastapi:
    name: Package FastAPI Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package FastAPI application
        run: |
          mkdir -p artifact
          cp -r app artifact/
          cp -r alembic artifact/
          cp requirements.txt artifact/

      - name: Upload FastAPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: fastapi-server
          path: artifact/
